// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cajasqlserver.Models;

namespace cajasqlserver.Migrations
{
    [DbContext(typeof(DbContexto))]
    [Migration("20200211160008_Primera-migracion")]
    partial class Primeramigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cajasqlserver.Models.t_caja", b =>
                {
                    b.Property<int>("idtcaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_cierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("rtipocajaidtipocaja")
                        .HasColumnType("int");

                    b.Property<int>("tipo")
                        .HasColumnType("int");

                    b.Property<string>("usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idtcaja");

                    b.HasIndex("rtipocajaidtipocaja");

                    b.ToTable("tcaja");
                });

            modelBuilder.Entity("cajasqlserver.Models.t_carpeta", b =>
                {
                    b.Property<int>("idcarpeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("caja")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_cierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<int>("nit")
                        .HasColumnType("int");

                    b.Property<int?>("rcajaidtcaja")
                        .HasColumnType("int");

                    b.HasKey("idcarpeta");

                    b.HasIndex("rcajaidtcaja");

                    b.ToTable("tcarpeta");
                });

            modelBuilder.Entity("cajasqlserver.Models.t_tipo_caja", b =>
                {
                    b.Property<int>("idtipocaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idtipocaja");

                    b.ToTable("ttipocaja");
                });

            modelBuilder.Entity("cajasqlserver.Models.t_caja", b =>
                {
                    b.HasOne("cajasqlserver.Models.t_tipo_caja", "rtipocaja")
                        .WithMany("lcaja")
                        .HasForeignKey("rtipocajaidtipocaja");
                });

            modelBuilder.Entity("cajasqlserver.Models.t_carpeta", b =>
                {
                    b.HasOne("cajasqlserver.Models.t_caja", "rcaja")
                        .WithMany("lcarpeta")
                        .HasForeignKey("rcajaidtcaja");
                });
#pragma warning restore 612, 618
        }
    }
}
